### ISSUE TITLE
Build onload on kernel > 6.0

### ISSUE THREAD

**Issue by YungeG** [Xilinx-CNS/onload#128]
lastest onload build will fail on kernel > 6.0, prompting 
`No rule to make target 'vmlinux.o', needed by 'modpost'.`

**Comment by ol-alexandra** [comment]
It is very strange, `make HAVE_SFC=0` works for us with linux-6.0 and linux-6.1.  @ol-sergeyn do you remember such an issue?

**Comment by ol-alexandra** [comment]
If I recall correctly, than it is an issue with some Linux kernels and with some Linux distributions.  And you get this message when you try to build any module, onload or not.

**Comment by ol-sergeyn** [comment]
> It is very strange, `make HAVE_SFC=0` works for us with linux-6.0 and linux-6.1. @ol-sergeyn do you remember such an issue?

Yes, we've fixed it once in #114

**Comment by YungeG** [comment]
Thank you very much !

**Comment by ivatet-amd** [comment]
@YungeG Is there still an issue in your setup? I believe Onload should build on 6.1 after the recent SFC driver update.

**Comment by ivatet-amd** [comment]
Assuming it is a no, closing. Please re-open if the issue is still the case.

**Comment by YungeG** [comment]
No Problem anymore, after modifying Makefile according to https://github.com/Xilinx-CNS/onload/issues/114 .
Sorry for late response .
